version: '3.7'
services:
  db:
    image: postgres:15
    container_name: booking_db
    volumes:
      - postgresdata:/var/lib/postgresql/data
    env_file:
      - .env-non-dev
    ports:
      - 5432:5432

  redis:
    image: redis:7
    container_name: redis_db
    env_file:
      - .env-non-dev

  crud:
    build: .
    container_name: crud
    env_file:
      - .env-non-dev
    depends_on:
      - db
      - redis
    command: sh -c "gunicorn main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    ports:
      - 7000:8000

  celery:
    build: .
    container_name: amessage_celery
    env_file:
      - .env-non-dev
    depends_on:
      - redis
    command: sh -c "celery --app=tasks.celery_app:celery worker -l INFO"