"""empty message

Revision ID: 84f3af0b4265
Revises: 
Create Date: 2024-04-25 15:06:03.479290

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "84f3af0b4265"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=15), nullable=False),
        sa.Column("registered_at", sa.DateTime(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("email", sa.String(length=30), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("is_banned", sa.Boolean(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("image_url", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_index("idx_email", "users", ["email"], unique=False)
    op.create_index("idx_username", "users", ["username"], unique=False)
    op.create_table(
        "posts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=25), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.String(length=2000), nullable=False),
        sa.Column("date_of_publication", sa.DateTime(), nullable=False),
        sa.Column("date_of_update", sa.DateTime(), nullable=False),
        sa.Column("likes", sa.Integer(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "films",
                "series",
                "games",
                "sport",
                "other",
                "programming",
                name="category",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_post_date_of_publication",
        "posts",
        ["date_of_publication"],
        unique=False,
    )
    op.create_index("idx_post_title", "posts", ["title"], unique=False)
    op.create_index("idx_post_user_id", "posts", ["user_id"], unique=False)
    op.create_table(
        "comments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(length=300), nullable=False),
        sa.Column("created_at", sa.Date(), nullable=False),
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["post_id"], ["posts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_comments_created_at", "comments", ["created_at"], unique=False
    )
    op.create_table(
        "likes",
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["post_id"], ["posts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("post_id", "user_id"),
    )
    op.create_index("idx_likes_post_id", "likes", ["post_id"], unique=False)
    op.create_index("idx_likes_user_id", "likes", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_likes_user_id", table_name="likes")
    op.drop_index("idx_likes_post_id", table_name="likes")
    op.drop_table("likes")
    op.drop_index("idx_comments_created_at", table_name="comments")
    op.drop_table("comments")
    op.drop_index("idx_post_user_id", table_name="posts")
    op.drop_index("idx_post_title", table_name="posts")
    op.drop_index("idx_post_date_of_publication", table_name="posts")
    op.drop_table("posts")
    op.drop_index("idx_username", table_name="users")
    op.drop_index("idx_email", table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
