"""empty message

Revision ID: f4ad2e022c0b
Revises: 71f3a47f301d
Create Date: 2024-04-25 15:10:12.841877

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f4ad2e022c0b"
down_revision: Union[str, None] = "71f3a47f301d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "posts",
        "category",
        existing_type=postgresql.ENUM(
            "films",
            "series",
            "games",
            "sport",
            "other",
            "programming",
            name="category",
        ),
        type_=sa.String(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "posts",
        "category",
        existing_type=sa.String(),
        type_=postgresql.ENUM(
            "films",
            "series",
            "games",
            "sport",
            "other",
            "programming",
            name="category",
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
